export default class Column {
    static _template(): any;
    _construct(): void;
    _smooth: boolean | undefined;
    _independentNavigation: any;
    _itemSpacing: any;
    _itemPosX: any;
    _itemPosY: any;
    _scrollIndex: any;
    _whenEnabled: Promise<any> | undefined;
    _firstEnable: ((value: any) => void) | undefined;
    debounceDelay: any;
    _update: any;
    _updateImmediate: any;
    _init(): void;
    h: any;
    get _itemTransition(): any;
    _focus(): void;
    _unfocus(): void;
    selectNext(): any;
    selectPrevious(): any;
    _shouldScroll(): any;
    shouldScrollUp(): boolean;
    shouldScrollDown(): boolean;
    render(next: any, prev: any): void;
    _prevLastScrollIndex: number | undefined;
    checkSkipPlinko(prev: any, next: any): any;
    _performRender(): void;
    get onScreenItems(): any;
    _isOnScreen(child: any): boolean;
    _updateLayout(): void;
    _lastScrollIndex: number | undefined;
    set independentNavigation(arg: any);
    get independentNavigation(): any;
    set itemSpacing(arg: any);
    get itemSpacing(): any;
    set scrollIndex(arg: any);
    get scrollIndex(): any;
    set itemPosX(arg: any);
    get itemPosX(): any;
    set itemPosY(arg: any);
    get itemPosY(): any;
    get _itemsY(): any;
    appendItems(items?: any[]): void;
    setParentToItems(): void;
    scrollTo(index: any, duration?: number): void;
    selectedIndex: any;
    $itemChanged(): void;
    $removeItem(item: any): void;
    $columnChanged(): void;
    onScreenEffect(): void;
}
//# sourceMappingURL=index.lng.d.ts.map