name: E2E Template App (Android)

defaults:
    run:
        shell: zsh -l {0}
on:
    workflow_dispatch:
    push:
        branches:
            - main
            - 'release/**'
        paths-ignore:
            - 'docs/**'
            - '**/README.md'
    pull_request:
        types: [labeled]

jobs:
    e2e-template-android:
        if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || github.event.label.name == 'e2e-template-android' || github.event.label.name == 'e2e' }}
        runs-on: [self-hosted, macos]
        env:
            GHP_AUTH_TOKEN: ${{ secrets.GHP_AUTH_TOKEN }}
        steps:
            - uses: actions/checkout@v2
            - name: Setup
              run: |
                  yarn config set network-timeout 300000
            - name: Bootstrap
              run: |
                  yarn bootstrap-clean
            - name: E2E Template App Android
              run: |
                  yarn e2e-template-android
